plugins {
    id 'com.android.application'
}

android {
    namespace "com.handfx"

    compileSdk 34

    defaultConfig {
        applicationId "com.handfx"
        minSdk 26
        targetSdk 34

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "../CMakeLists.txt"
        }
    }
}

dependencies {
}
